CREATE DATABASE IF NOT EXISTS alumni_db;
USE alumni_db;

CREATE TABLE IF NOT EXISTS alumni (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  roll_no VARCHAR(20) NOT NULL UNIQUE,
  year INT,
  branch VARCHAR(50),
  email VARCHAR(100),
  phone VARCHAR(20),
  job VARCHAR(100)
);
